-- Phase 8 AP1 (Sichere Fachadministration - Auth-Grundlage fuer
-- Admin-/Konfigurationsflaechen, siehe PHASE_8_IMPLEMENTATION_PLAN.md
-- Abschnitt 3.1/4). Rein additive Migration (neue nullable Spalte, keine
-- Datenaenderung) -- kein Vorab-Datencheck noetig.
--
-- `password_hash` ist NULL fuer alle bestehenden/zukuenftigen Nutzer, die
-- sich weiterhin nur ueber den bestehenden `dev-login` (Beratungsfluss,
-- kein Passwort) anmelden. Nur die neuen synthetischen Admin-Testnutzer
-- (config_editor/config_publisher, siehe AP2) erhalten einen Wert.
-- Format des gespeicherten Werts: "<salt-hex>:<hash-hex>" (scrypt via
-- node:crypto, src/server/auth/password.ts) -- kein Klartext-Passwort wird
-- je persistiert.
ALTER TABLE "users" ADD COLUMN "password_hash" TEXT;
